[settings]
lockfile = true

[tools]
age = 'latest'
gopass = 'latest'
direnv = 'latest'
nodejs = 'latest'
node = 'latest'
bun = 'latest'
gh = 'latest'
glab = 'latest'
aws-cli = 'latest'
pipx = 'latest'
"npm:mcp-remote" = 'latest'
"pipx:mcp-atlassian" = "0.21.1"
